test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,4 +30,49 @@ jobs:
           echo "REDIS_PORT=6379" >> .env
           echo "REDIS_DB=0" >> .env
 
+      - name: Démarrer le conteneur
+        run: docker compose up -d
 
+      - name: Attendre MySQL
+        run: |
+          sleep 10
+          timeout=60
+          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
+            echo "Waiting for MySQL..."
+            sleep 3
+            timeout=$((timeout - 3))
+            if [ $timeout -le 0 ]; then
+              echo "MySQL failed to start"
+              exit 1
+            fi
+          done
+          sleep 5
+
+      - name: Exécuter test_user.py (TODO - inclure tous les tests)
+        working-directory: src
+        run: |
+          python3 -m pytest
+
+
+      - name: Déploiement
+        working-directory: src
+        run: echo "TODO - Faire le déploiement"
+
+      - name: Cleanup
+        if: always()
+        run: docker compose down -v
+
+
+  deploy:
+    runs-on: self-hosted
+    needs: test   # Ne se lance que si les tests passen
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Déploiement local
+        run: |
+          cd $GITHUB_WORKSPACE
+          echo "Déploiement sur la VM en cours..."
+
+          docker compose down || true
+          docker compose up -d --build    
